// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Image: typeof import('./../components/widget/Media/ImageWidget/Image.vue')['default']
    NaiveProvider: typeof import('./../components/common/NaiveProvider.vue')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./../components/widget/Common/TextWidget/Text.vue')['default']
  }
}
